#!/bin/bash

# Synchronisation des sites de dévelopement et de production pour mes dossiers techniques en ligne

# Constantes pour simuler un booléen
VRAI=1
FAUX=0

synchronise() {
	local version
	local dossier
	if [[ $1 -eq $VRAI ]]; then
		version="production"
		dossier="dossiers-techniques"
	else
		version="développement"
		dossier="devDT"
	fi
	echo "Mes dossiers techniques en ligne: synchronisation du site de $version"
	rsync -e ssh -av --delete-after public src sc2rogu0302@marigane.o2switch.net:~/${dossier}/
}

# Fonction pour afficher l'aide
show_help() {
	echo "Synchronisation du site VolÉval.net"  # Titre de l'aide
	echo "Utilisation : maj-site [option]"  # Instructions générales
	echo "option : dev pour développement, prod pour production"  # Options possibles
	echo "Exemple : maj-site prod pour mettre à jour le site de production"  # Exemple d'utilisation
}

# Programme principal ============================================================
case "$1" in
	--help)
		show_help
		exit 0
		;;
	dev)
		synchronise $FAUX
		exit 0
		;;
	prod)
		synchronise $VRAI
		exit 0
		;;
	*)
		echo "Paramètre inconnu"
		exit 1
		;;
esac
