<?php // nomenclature du cric bouteille
Ligne_nomenclature( 1, 1, 'Embase de cric',							'EN AW-2017',	'', 'Embase');
Ligne_nomenclature( 2, 1, 'Corps de pompe',							'EN AW-2017',	'', 'Corps2pompe');
Ligne_nomenclature( 3, 1, 'Piston de pompe',							'S 235',			'', 'piston_pompe');
Ligne_nomenclature( 4, 2, 'Axe d&apos;articulation',				'S 235',			'', 'axe_articulation');
Ligne_nomenclature( 5, 4, 'Segment d&apos;arr&ecirc;t radial 6 x 0,7','',		'', 'segment_arret');
Ligne_nomenclature( 6, 1, 'Articulation',								'EN AW-2017',	'', 'articulation');
Ligne_nomenclature( 7, 1, 'Piston r&eacute;cepteur',				'EN AW-2017',	'', 'piston_recepteur');
Ligne_nomenclature( 8, 1, 'Couvercle',									'EN AW-2017',	'', 'Couvercle');
Ligne_nomenclature( 9, 1, 'Cylindre principal',						'PMMA',			'Polym&eacute;thylm&eacute;thacrylate', 'cylindre_principal');
Ligne_nomenclature(10, 1, 'R&eacute;servoir',						'PMMA',			'Polym&eacute;thylm&eacute;thacrylate', 'reservoir');
Ligne_nomenclature(11, 4, '&Eacute;crou M4',							'',				'', 'ecrouM4');
Ligne_nomenclature(12, 4, 'Rondelle M4',								'',				'', 'rondelleM4');
Ligne_nomenclature(13, 4, 'Tirant',										'S 235',			'', 'tirant');
Ligne_nomenclature(14, 1, 'Biellette',									'S 235',			'', 'biellette');
Ligne_nomenclature(15, 1, 'Axe d&apos;articulation de chape',	'',				'', 'axe_chape');
Ligne_nomenclature(16, 1, 'Pointeau',									'',				'Vis sans t&ecirc;te à bout plat HC M10-30 modifi&eacute;e', 'pointeau');
Ligne_nomenclature(17, 1, 'Joint de pointeau de retour',			'',				'', 'joint2pointeau');
Ligne_nomenclature(18, 1, 'Chandelle',									'EN AW-2017',	'', 'Chandelle');
Ligne_nomenclature(19, 1, 'Bille de tarage',							'',				'', 'bille_tarage');
Ligne_nomenclature(20, 1, 'Poussoir de tarage',						'S 185',			'', 'poussoir2tarage');
Ligne_nomenclature(21, 1, 'Ressort de tarage',						'C 60',			'', 'ressort2tarage');
Ligne_nomenclature(22, 1, 'Vis de tarage',							'S 185',			'', 'vis2tarage');							
Ligne_nomenclature(23, 1, 'Bouchon de tarage',						'',				'', 'bouchon_tarage');
Ligne_nomenclature(24, 1, 'Joint plat de bouchon de tarage',	'',				'', 'joint2tarage');
Ligne_nomenclature(25, 1, 'Bouchon de remplissage',				'',				'', 'bouchon2remplissage');
Ligne_nomenclature(26, 1, 'Bille d&apos;admission',				'',				'', 'bille_admission');
Ligne_nomenclature(27, 1, 'Joint de pompe',							'',				'', 'joint2pompe');
Ligne_nomenclature(28, 1, 'Joint torique de piston',				'',				'', 'joint2piston');
Ligne_nomenclature(29, 1, 'Vis de fixation du corps de pompe',	'',				'', 'vis2fixation_du_corps2pompe');
Ligne_nomenclature(30, 1, 'Levier',										'S 185',			'', 'levier');
Ligne_nomenclature(31, 1, 'Joint torique de r&eacute;servoir',	'',				'', 'joint2reservoir');
Ligne_nomenclature(32, 1, 'Joint torique de corps de pompe',	'',				'', 'joint_torique2corps2pompe');
