<?php // nomenclature du cric bouteille
Ligne_nomenclature( 1, 1, 'Embase de cric',							'','', 'Embase');
Ligne_nomenclature( 2, 1, 'Corps de pompe',							'','', 'Corps2pompe');
Ligne_nomenclature( 3, 1, 'Piston de pompe',							'','', 'piston_pompe');
Ligne_nomenclature( 4, 2, 'Axe d&#165;articulation',				'','', 'axe_articulation');
Ligne_nomenclature( 5, 4, 'Segment d&#145;arrêt radial 6 x 0,7','','', 'segment_arret');
Ligne_nomenclature( 6, 1, 'Articulation',								'','', 'articulation');
Ligne_nomenclature( 7, 1, 'Piston r&eacute;cepteur',				'','', 'piston_recepteur');
Ligne_nomenclature( 8, 1, 'Couvercle',									'','', 'Couvercle');
Ligne_nomenclature( 9, 1, 'Cylindre principal',						'','', 'cylindre_principal');
Ligne_nomenclature(10, 1, 'R&eacute;servoir',						'','', 'reservoir');
Ligne_nomenclature(11, 4, '&Eacute;crou M4',							'','', 'ecrouM4');
Ligne_nomenclature(12, 4, 'Rondelle M4',								'','', 'rondelleM4');
Ligne_nomenclature(13, 4, 'Tirant',										'','', 'tirant');
Ligne_nomenclature(14, 1, 'Biellette',									'','', 'biellette');
Ligne_nomenclature(15, 1, 'Axe d&#165;articulation de chape',	'','', 'axe_chape');
Ligne_nomenclature(16, 1, 'Pointeau',									'','', 'pointeau');
Ligne_nomenclature(17, 1, 'Joint de pointeau de retour',			'','', 'joint2pointeau');
Ligne_nomenclature(18, 1, 'Chandelle',									'','', 'Chandelle');
Ligne_nomenclature(19, 1, 'Bille de tarage',							'','', 'bille_tarage');
Ligne_nomenclature(20, 1, 'Poussoir de tarage',						'','', 'poussoir2tarage');
Ligne_nomenclature(21, 1, 'Ressort de tarage',						'','', 'ressort2tarage');
Ligne_nomenclature(22, 1, 'Vis de tarage',								'','', 'vis2tarage');							
Ligne_nomenclature(23, 1, 'Bouchon de tarage',						'','', 'bouchon_tarage');
Ligne_nomenclature(24, 1, 'Joint plat de bouchon de tarage',	'','', 'joint2tarage');
Ligne_nomenclature(25, 1, 'Bouchon de remplissage',				'','', 'bouchon2remplissage');
Ligne_nomenclature(26, 1, 'Bille d&#165;admission',				'','', 'bille_admission');
Ligne_nomenclature(27, 1, 'Joint de pompe',							'','', 'joint2pompe');
Ligne_nomenclature(28, 1, 'Joint torique de piston',				'','', 'joint2piston');
Ligne_nomenclature(29, 1, 'Vis de fixation du corps de pompe',	'','', 'vis2fixation_du_corps2pompe');
Ligne_nomenclature(30, 1, 'Levier',										'','', 'levier');
Ligne_nomenclature(31, 1, 'Joint torique de réservoir',			'','', 'joint2reservoir');
Ligne_nomenclature(32, 1, 'Joint torique de corps de pompe',	'','', 'joint_torique2corps2pompe');
