<?php // nomenclature de la pince de marquage
Ligne_nomenclature( 1, 1, 'Support de v&eacute;rin',							'','', 'support2verin');
Ligne_nomenclature( 2, 1, 'Fond',													'','', 'fond');
Ligne_nomenclature( 3, 1, 'Plaque avant',											'','', 'plaque_avant');
Ligne_nomenclature( 4, 4, 'Goupile ISO 87-34-5x16-A',							'','', 'goupille');
Ligne_nomenclature( 5, 1, 'T&ocirc;le de protection',							'','', 'tole2protection');
Ligne_nomenclature( 6, 2, 'Vis &eacute;paul&eacute;e M5x40 NF E 27-191','','', 'vis_epauleeM5x40');
Ligne_nomenclature( 7, 4, 'Entretoise',											'','', 'entretoise');
Ligne_nomenclature( 8, 1, 'Bras sup&eacute;rieur',								'','', 'bras_superieur');
Ligne_nomenclature( 9, 1, 'Bras inf&eacute;rieur',								'','', 'bras_inferieur');
Ligne_nomenclature(10, 1, 'Carter sup&eacute;rieur',							'','', 'carter_superieur');
Ligne_nomenclature(11, 1, 'Carter inf&eacute;rieur',							'','', 'carter_inferieur');
Ligne_nomenclature(12, 1, 'Corps v&eacute;rin PES 32 P NA 254',			'','', 'corps_verin');
Ligne_nomenclature(13, 1, 'Piston PES 32 NA 25 DM4',							'','', 'piston', 'piston','.EASM');
Ligne_nomenclature(14, 1, 'Came',													'','', 'came');
Ligne_nomenclature(15, 1, 'Axe',														'','', 'axe');
Ligne_nomenclature(16, 1, 'Entretoise ep. 1.8',									'','', 'entretoise_ep1.8');
Ligne_nomenclature(17, 1, 'Enclume',												'','', 'enclume');
Ligne_nomenclature(18, 1, 'Plaque d&apos;appui',								'','', 'plaque_dappui');
Ligne_nomenclature(19, 1, 'Poinçon',												'','', 'poincon');
Ligne_nomenclature(20, 1, 'Roulement SNR 624EE',								'','', 'roulement',2,'.EASM');
Ligne_nomenclature(21,13, 'Vis FHC NF E 27-160M3X0,5-8-8.8',				'','', 'visFHC');
Ligne_nomenclature(22, 8, 'Vis CZX NF E25-11 M3-0,5-10-4,8-1',				'','', 'visCZX');
Ligne_nomenclature(23, 1, 'Vis sans t&ecirc;te &agrave; bout plat NF E-27-180 M3x0,5-8-3,3h','','', 'vis_sans_tete',6);
Ligne_nomenclature(24, 8, 'Vis ISO 4762-M5x16-8.8',							'','', 'visISO');
Ligne_nomenclature(25, 1, 'Ressort de rappel',									'','', 'ressort');
