<?php // nomenclature de la cambreuse
Ligne_nomenclature( 1, 1,	'Table',											'',				'non repr&eacute;sent&eacute;e',	'Table');
Ligne_nomenclature( 2, 1,	'Corps de v&eacute;rin ISO 6431 63X50',				'',				'',				'corps2verin',	'corps2verin', '.EASM');
Ligne_nomenclature( 3, 1,	'Corps de v&eacute;rin ISO 6431 80X50',				'',				'',				'corps2verin2',	'corps2verin2', '.EASM');
Ligne_nomenclature( 4, 1,	'Tige de v&eacute;rin ISO 6431 63X50',				'',				'',				'tige2verin',	'tige2verin', '.EASM');
Ligne_nomenclature( 5, 1,	'Tige de v&eacute;rin ISO 6431 80X50',				'',				'',				'tige2verin2',	'tige2verin2', '.EASM');
Ligne_nomenclature( 6, 1,	'Vis H M8x65',										'',				'NF EN ISO 4017','visHM8x65');
Ligne_nomenclature( 7, 1,	'Basculeur usin&eacute;',							'EN AW 2017',	'',				'basculeur');
Ligne_nomenclature( 8, 1,	'Axe de bielle',									'C 40',			'',				'axe2bielle');
Ligne_nomenclature( 9, 2,	'Coussinet 12-18x12',								'CW 453K',		'ISO 2795',		'coussinet12-18x12');
Ligne_nomenclature(10, 1,	'Bielle',											'E 335',		'',				'bielle');
Ligne_nomenclature(11, 3,	'Coussinet 12-18x16',								'CW 453K',		'ISO 2795',		'coussinet12-18x16');
Ligne_nomenclature(12, 1,	'Coussinet 16-22x16',								'CW 453K',		'ISO 2795',		'coussinet16-22x16');
Ligne_nomenclature(13, 1,	'Chape',											'S 235',		'',				'chape');
Ligne_nomenclature(14, 1,	'Axe de chape',										'C 40',			'',				'Axe2chape');
Ligne_nomenclature(15, 1,	'But&eacute;e',										'S 235',		'',				'butee');
Ligne_nomenclature(16, 1,	'Bride de blocage',									'C 40',			'Tremp&eacute;','Bride2blocage');
Ligne_nomenclature(17, 1,	'Bride',											'C 40',			'',				'Bride');
Ligne_nomenclature(18, 2,	'Flasque',											'EN AW 2017',	'',				'Flasque');
Ligne_nomenclature(19, 1,	'Plaque de support de v&eacute;rin de cambrage',	'',				'',				'Plaque_cambrage');
Ligne_nomenclature(20, 1,	'Plaque de support de v&eacute;rin de bridage',		'',				'',				'Plaque_bridage');
Ligne_nomenclature(21, 1,	'Cale',												'EN AW 2017',	'',				'Cale');
Ligne_nomenclature(22, 4,	'Support de fixation',								'S 235',		'',				'Support2fixation');
Ligne_nomenclature(23, 4,	'Bride d&apos;arbre',								'S 235',		'',				'Bride_darbre');
Ligne_nomenclature(24, 2,	'Tige de guidage',									'',				'',				'Tige2guidage');
Ligne_nomenclature(25, 1,	'Plaque support de posoir',							'S 235',		'',				'Plaque_support2posoir');
Ligne_nomenclature(26, 1,	'Support de vis d&apos;arr&ecirc;t',				'S 235',		'',				'Support2vis_darret');
Ligne_nomenclature(27, 2,	'Support d&apos:axe d&apos;&eacute;querre',			'',				'',				'Support_daxe_dequerre');
Ligne_nomenclature(28, 2,	'Axe d&apos;&eacute;querre',						'',				'',				'Axe_dequerre');
Ligne_nomenclature(29, 1,	'&Eacute;crou H M8',								'',				'ISO EN 4032',	'EcrouHM8');
Ligne_nomenclature(30,20,	'Vis CHC M6-16-14',									'',				'',				'CHCM6-16-14');
Ligne_nomenclature(31,16,	'Vis CHC M8-16-14',									'',				'',				'CHCM8-16-14');
Ligne_nomenclature(32, 1,	'Support de but&eacute;e',							'C 40',			'',				'Support2butee');
Ligne_nomenclature(33, 5,	'But&eacute;e de positionnement ext&eacute;rieure',	'C 40',			'',				'Butee2positionnement_ext');
Ligne_nomenclature(34, 2,	'Goupille 3 x 20',									'',				'ISO 8752',		'Goupille3x20');
Ligne_nomenclature(35, 4,	'Vis t&ecirc;te frais&eacute;e M6-12',				'',				'ISO 10642',	'VisFSM6-12');
Ligne_nomenclature(36, 1,	'Appui fil d=8 L = 150',							'',				'',				'Appui_fil_d8_L150');
Ligne_nomenclature(37, 1,	'Branche gauche',									'',				'',				'branche_gauche');
Ligne_nomenclature(38, 1,	'Branche droite',									'',				'',				'branche_droite', 'branche_droite', '.EASM');
